#!/usr/bin/env python3
"""
Generate interpretation prompt files for factor poles.

For each pole, this script assembles a complete prompt containing:
1. System prompt
2. User prompt
3. Mean group scores
4. Factor loadings
5. Plain-text example excerpts, with loading words appended

Inputs:
    factors/f<n>_pos.txt
    factors/f<n>_neg.txt
    examples_txt/f<n>_<pole>/*.txt
    examples/score_details.txt
    sas/output_cl_st2_ph2_arianne/means_group_f<n>.tsv

Output:
    interpretation/input/f<n>_<pole>.txt

Important:
    Run these first:
        python examples.py
        python score_details.py
        python examples_txt.py
"""

import re
from pathlib import Path

# ============================================================
# PATHS
# ============================================================
FACTORS_DIR = Path("factors")
EXAMPLES_DIR = Path("examples_txt")
DETAILS_FILE = Path("examples/score_details.txt")
MEANS_DIR = Path("sas/output_cl_st2_ph2_arianne")
OUTPUT_DIR = Path("interpretation/input")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================
# PROMPTS
# ============================================================

SYSTEM_PROMPT = """You are a corpus linguist specializing in Lexical Multi-Dimensional Analysis (LMDA).
Your task is to interpret a single factor pole as a discourse dimension.

The corpus comes from an oral-history style interview project in which people living in the USA
during the COVID-19 pandemic were interviewed. The corpus includes:
• Human interviewee responses
• Synthetic responses generated by GPT, Grok, and Gemini

The LLM-generated responses were produced under two prompting regimes:
1. A plain prompt, which instructed the model to speak as a person living in the USA
   during the pandemic and respond to interview questions.
2. An enhanced/persona prompt, which additionally supplied background demographic/biographical
   information and a list of thematic points that the LLM should incorporate into its answers.

Your interpretation must identify the discourses encoded at this pole, taking into account:
• Linguistic loadings, which represent the entire corpus
• The example excerpts, which illustrate high-scoring texts at this pole
"""

USER_PROMPT = """Interpret Factor {factor} ({polarity}) as a discourse dimension.
Propose possible labels for this pole only and justify them.

Base your interpretation on:
• Mean group scores. For positive poles, consider the highest-scoring groups in the table. For negative poles, consider the lowest-scoring groups.
• Factor loadings
• Example excerpts from high-scoring texts
• The loading words that appear in these examples
• Which group is driving the pole, including whether it is human or LLM-generated and, where applicable, prompt type.
• Do not offer a 'versus' dimension label. Focus on this single pole only.

Give equal weight to the loadings and the examples. Remember that loadings represent the full corpus,
whereas the excerpts are only selected high-scoring samples.
"""

# ============================================================
# LOAD SCORE DETAILS
# ============================================================

def load_score_details(details_path: Path) -> dict[str, dict[str, dict[str, list[str]]]]:
    """
    Parse score_details.txt into:
        score_details[text_id][factor]["pos" or "neg"] = list_of_words

    Example:
        score_details["t000350"]["f1"]["neg"] = ["word1", "word2"]
    """
    if not details_path.exists():
        raise FileNotFoundError(
            f"Score details file not found: {details_path}\n"
            "Run `python score_details.py` first."
        )

    score_details: dict[str, dict[str, dict[str, list[str]]]] = {}
    current_id = None
    current_factor = None

    with open(details_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Example: "text ID: t000001"
            m = re.match(r"text ID:\s*(t\d+)", line)
            if m:
                current_id = m.group(1)
                score_details[current_id] = {}
                continue

            # Example: "f2 score:"
            m = re.match(r"(f\d+)\s+score:", line)
            if m and current_id:
                current_factor = m.group(1)
                score_details[current_id][current_factor] = {"pos": [], "neg": []}
                continue

            # Example: "f2 pos words (N=...): word, word"
            m = re.match(r"f\d+\s+(pos|neg)\s+words.*:\s*(.*)", line)
            if m and current_id and current_factor:
                pole = m.group(1)
                words_str = m.group(2).strip()
                words = [w.strip() for w in words_str.split(",") if w.strip()]
                score_details[current_id][current_factor][pole] = words

    return score_details

# ============================================================
# EXCERPT EXTRACTOR
# ============================================================

def extract_excerpt(file_path: Path, n_lines: int = 30) -> str:
    """
    Extract the first n_lines from a plaintext example file.

    The plaintext example already contains a useful header:
        Text ID
        Group
        Source
        Model
        Score
        Loading words
    """
    lines = []

    with open(file_path, "r", encoding="utf-8") as f:
        for _ in range(n_lines):
            line = f.readline()
            if not line:
                break
            lines.append(line.rstrip("\n"))

    return "\n".join(lines)


def extract_text_id_from_example(file_text: str) -> str | None:
    """
    Extract text ID from examples_txt output.

    Preferred pattern:
        Text ID: t000350

    Fallback:
        any t000350-style ID in the file
    """
    m = re.search(r"^Text ID:\s*(t\d+)", file_text, re.MULTILINE)
    if m:
        return m.group(1)

    m = re.search(r"\b(t\d+)\b", file_text)
    if m:
        return m.group(1)

    return None

# ============================================================
# FACTOR FILE DISCOVERY
# ============================================================

def factor_sort_key(path: Path) -> tuple[int, int]:
    """
    Sort factor files numerically and by pole.

    Example order:
        f1_pos.txt
        f1_neg.txt
        f2_pos.txt
        f2_neg.txt
    """
    m = re.fullmatch(r"f(\d+)_(pos|neg)", path.stem)

    if not m:
        return (999999, 999999)

    fac_num = int(m.group(1))
    pole_order = 0 if m.group(2) == "pos" else 1

    return fac_num, pole_order


def discover_factor_files() -> list[Path]:
    """
    Return only factor files matching:
        f<n>_pos.txt
        f<n>_neg.txt
    """
    files = []

    for path in FACTORS_DIR.glob("f*_*.txt"):
        if re.fullmatch(r"f\d+_(pos|neg)", path.stem):
            files.append(path)

    files = sorted(files, key=factor_sort_key)

    if not files:
        raise FileNotFoundError(f"No factor pole files found in {FACTORS_DIR}")

    return files

# ============================================================
# MAIN SCRIPT
# ============================================================

def main() -> None:
    if not EXAMPLES_DIR.exists():
        raise FileNotFoundError(
            f"Plaintext examples directory not found: {EXAMPLES_DIR}\n"
            "Run `python examples_txt.py` first."
        )

    score_details = load_score_details(DETAILS_FILE)
    factor_files = discover_factor_files()

    for factor_file in factor_files:
        factor_name = factor_file.stem          # e.g. "f1_pos"
        factor, polarity = factor_name.split("_")

        # Load factor loadings text.
        loadings_text = factor_file.read_text(encoding="utf-8").strip()

        # Load mean group scores.
        means_file = MEANS_DIR / f"means_group_{factor}.tsv"

        if not means_file.exists():
            print(f"Warning: missing means file {means_file}")
            means_text = "(No means file found)"
        else:
            means_text = means_file.read_text(encoding="utf-8").strip()

        # Load example files.
        example_folder = EXAMPLES_DIR / factor_name

        if not example_folder.exists():
            raise FileNotFoundError(
                f"Example folder not found: {example_folder}\n"
                "Run `python examples_txt.py` first."
            )

        example_files = sorted(example_folder.glob("*.txt"))[:10]

        if not example_files:
            raise FileNotFoundError(
                f"No plaintext examples found in {example_folder}\n"
                "Run `python examples_txt.py` first and check for missing files."
            )

        excerpts_block = []

        for ex_path in example_files:
            file_text = ex_path.read_text(encoding="utf-8")
            excerpt = extract_excerpt(ex_path, n_lines=30)

            tid = extract_text_id_from_example(file_text)

            if not tid:
                print(f"Warning: no text ID found in {ex_path}")
                tid = "UNKNOWN"

            loading_words = score_details.get(tid, {}).get(factor, {}).get(polarity, [])
            lw_string = ", ".join(loading_words) if loading_words else "(none)"

            excerpt_block = (
                f"\n===== EXCERPT: {ex_path.name} (text ID {tid}) =====\n"
                f"{excerpt}\n"
                f"\n--- Loading words for this example ({polarity}): {lw_string}\n"
            )

            excerpts_block.append(excerpt_block)

        # Assemble final prompt.
        system_final = SYSTEM_PROMPT
        user_final = USER_PROMPT.format(factor=factor, polarity=polarity)
        mean_final = f"\n=== MEAN GROUP SCORES ===\n{means_text}\n"
        loadings_final = f"\n=== FACTOR LOADINGS ({factor_name}) ===\n{loadings_text}\n"

        final_prompt = (
                system_final
                + "\n\n"
                + user_final
                + "\n"
                + mean_final
                + loadings_final
                + "\n=== EXAMPLE EXCERPTS ===\n"
                + "\n".join(excerpts_block)
        )

        out_path = OUTPUT_DIR / f"{factor_name}.txt"
        out_path.write_text(final_prompt, encoding="utf-8")

        print("Wrote:", out_path)


if __name__ == "__main__":
    main()